### PR TITLE
Two failed examples in specs

### PR DESCRIPTION
**Pull request by yevgenko**
```
All examples were filtered out; ignoring {:focus=>true}
.....................F....F.......

Failures:

  1) Strano::Repo#cloned? 
    Failure/Error: it { repo.cloned?.should == true }
      expected: true
            got: false (using ==)
    # ./spec/lib/strano/repo_spec.rb:59:in `block (3 levels) in <top (required)>'

  2) Project should set the github data after save
    Failure/Error: @project.github_data.should_not be_empty
    NoMethodError:
      undefined method `github_data' for #<Project:0x0000000a3de348>
    # ./spec/models/project_spec.rb:15:in `block (2 levels) in <top (required)>'

Finished in 12.18 seconds
34 examples, 2 failures

Failed examples:

rspec ./spec/lib/strano/repo_spec.rb:59 # Strano::Repo#cloned? 
rspec ./spec/models/project_spec.rb:14 # Project should set the github data after save
```

### CODE REVIEW

**Comment by yevgenko** [comment]
Still to figure out [1) Strano::Repo#cloned?](https://github.com/joelmoss/strano/blob/master/spec/lib/strano/repo_spec.rb#L59)

**Comment by yevgenko** [comment]
[Build Status](https://travis-ci.org/yevgenko/strano) :sunglasses:

**Comment by yevgenko** [comment]
But you'll need #34 to recover the strano first

**Comment by joelmoss** [comment]
Tests are passing fine.

**Pull request closed without merging**
